import type { ExportTemplate } from '@/types/exportTemplates';

export const DEFAULT_COLOR_PALETTE = {
  primary: '#2563EB',
  secondary: '#64748B',
  accent: '#F97316',
  success: '#10B981',
  error: '#EF4444',
  warning: '#F59E0B',
  background: '#F8FAFC',
  textPrimary: '#1E293B',
  textSecondary: '#64748B',
  border: '#E2E8F0',
};

export const DEFAULT_FONT_SETTINGS = {
  primaryFont: 'Helvetica',
  monospaceFont: 'Courier',
  headingFont: 'Helvetica-Bold',
  baseFontSize: 10,
};

export const EXPORT_TEMPLATES: ExportTemplate[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    type: 'minimal',
    description: 'Single page with essential data only',
    branding: {
      colors: DEFAULT_COLOR_PALETTE,
      fonts: DEFAULT_FONT_SETTINGS,
    },
    layout: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 15, right: 15, bottom: 15, left: 15 },
      columns: 2,
    },
    sections: [
      { id: 'inspection_setup', name: 'Inspection Setup', enabled: true, order: 1 },
      { id: 'equipment', name: 'Equipment', enabled: true, order: 2 },
      { id: 'calibration', name: 'Calibration', enabled: true, order: 3 },
      { id: 'acceptance', name: 'Acceptance Criteria', enabled: true, order: 4 },
    ],
    includeWatermark: false,
    includeQRCode: false,
    includeTOC: false,
  },
  {
    id: 'standard',
    name: 'Standard',
    type: 'standard',
    description: '2-3 pages with all standard sections',
    branding: {
      colors: DEFAULT_COLOR_PALETTE,
      fonts: DEFAULT_FONT_SETTINGS,
    },
    layout: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 20, right: 20, bottom: 20, left: 20 },
      columns: 2,
    },
    sections: [
      { id: 'inspection_setup', name: 'Inspection Setup', enabled: true, order: 1 },
      { id: 'equipment', name: 'Equipment', enabled: true, order: 2 },
      { id: 'calibration', name: 'Calibration', enabled: true, order: 3 },
      { id: 'scan_parameters', name: 'Scan Parameters', enabled: true, order: 4 },
      { id: 'acceptance', name: 'Acceptance Criteria', enabled: true, order: 5 },
      { id: 'documentation', name: 'Documentation', enabled: true, order: 6 },
    ],
    includeWatermark: false,
    includeQRCode: false,
    includeTOC: false,
  },
  {
    id: 'comprehensive',
    name: 'Comprehensive',
    type: 'comprehensive',
    description: '6+ pages with drawings and diagrams',
    branding: {
      colors: DEFAULT_COLOR_PALETTE,
      fonts: DEFAULT_FONT_SETTINGS,
    },
    layout: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 20, right: 20, bottom: 20, left: 20 },
      columns: 1,
    },
    sections: [
      { id: 'cover_page', name: 'Cover Page', enabled: true, order: 1 },
      { id: 'inspection_setup', name: 'Inspection Setup', enabled: true, order: 2 },
      { id: 'equipment', name: 'Equipment', enabled: true, order: 3 },
      { id: 'calibration', name: 'Calibration', enabled: true, order: 4 },
      { id: 'calibration_drawing', name: 'Calibration Drawing', enabled: true, order: 5 },
      { id: 'part_diagram', name: 'Part Diagram', enabled: true, order: 6 },
      { id: 'scan_parameters', name: 'Scan Parameters', enabled: true, order: 7 },
      { id: 'acceptance', name: 'Acceptance Criteria', enabled: true, order: 8 },
      { id: 'documentation', name: 'Documentation', enabled: true, order: 9 },
    ],
    includeWatermark: true,
    includeQRCode: false,
    includeTOC: true,
  },
  {
    id: 'report',
    name: 'Report Mode',
    type: 'report',
    description: 'Full inspection report with scan images',
    branding: {
      colors: DEFAULT_COLOR_PALETTE,
      fonts: DEFAULT_FONT_SETTINGS,
    },
    layout: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 20, right: 20, bottom: 20, left: 20 },
      columns: 1,
    },
    sections: [
      { id: 'cover_page', name: 'Cover Page', enabled: true, order: 1 },
      { id: 'inspection_setup', name: 'Inspection Setup', enabled: true, order: 2 },
      { id: 'equipment', name: 'Equipment', enabled: true, order: 3 },
      { id: 'calibration', name: 'Calibration', enabled: true, order: 4 },
      { id: 'part_diagram', name: 'Part Diagram', enabled: true, order: 5 },
      { id: 'probe_details', name: 'Probe Details', enabled: true, order: 6 },
      { id: 'scan_details', name: 'Scan Details', enabled: true, order: 7 },
      { id: 'scan_images', name: 'Scan Images', enabled: true, order: 8 },
      { id: 'acceptance', name: 'Acceptance Criteria', enabled: true, order: 9 },
      { id: 'remarks', name: 'Remarks', enabled: true, order: 10 },
    ],
    includeWatermark: true,
    includeQRCode: true,
    includeTOC: true,
  },
  {
    id: 'audit',
    name: 'Audit Ready',
    type: 'audit',
    description: 'Complete documentation with signatures',
    branding: {
      colors: DEFAULT_COLOR_PALETTE,
      fonts: DEFAULT_FONT_SETTINGS,
    },
    layout: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 25, right: 25, bottom: 25, left: 25 },
      columns: 1,
    },
    sections: [
      { id: 'cover_page', name: 'Cover Page', enabled: true, order: 1 },
      { id: 'approval_signatures', name: 'Approval Signatures', enabled: true, order: 2 },
      { id: 'inspection_setup', name: 'Inspection Setup', enabled: true, order: 3 },
      { id: 'equipment', name: 'Equipment', enabled: true, order: 4 },
      { id: 'calibration', name: 'Calibration', enabled: true, order: 5 },
      { id: 'calibration_drawing', name: 'Calibration Drawing', enabled: true, order: 6 },
      { id: 'part_diagram', name: 'Part Diagram', enabled: true, order: 7 },
      { id: 'scan_parameters', name: 'Scan Parameters', enabled: true, order: 8 },
      { id: 'acceptance', name: 'Acceptance Criteria', enabled: true, order: 9 },
      { id: 'documentation', name: 'Documentation', enabled: true, order: 10 },
      { id: 'traceability', name: 'Traceability', enabled: true, order: 11 },
    ],
    includeWatermark: true,
    includeQRCode: true,
    includeTOC: true,
  },
];
